---
- name: install openstack on alpine-3.12
  hosts: openstack-1
  remote_user: testuser
  become: true


  roles: 
   -  deploy_MariaDB_on_alpine
   -  deploy_RabbitMQ_on_alpine
   -  deploy_Keystone_on_alpine
   -  deploy_Glance_on_alpine
   -  deploy_Cinder_on_alpine
   -  deploy_Swift_on_alpine
   -  deploy_Nova_on_alpine
   -  deploy_KVM_on_alpine
   -  deploy_Neutron_on_alpine
   -  deploy_Horizon_on_alpine
   -  deploy_Heat_on_alpine
   -  deploy_Ceilometr_on_alpine


