---
# tasks file for deploy_MariaDB_on_alpine
#
#
- name: uncomment a repo community
  replace:
         path: /etc/apk/repositories
         backup: yes
         regexp: '^#(.*[0-9]./community.*)'
         replace: '\1'

- name:  install MariaDB
  apk:
    name:  [ mariadb, mariadb-client, mariadb-connector-c ]
    state: present

- name: add mariadb-server.cnf from templates
  template:
    src: mariadb-server.cnf.j2 
    dest: /etc/my.cnf.d/mariadb-server.cnf
    mode: 0644

- find: paths=/var/lib/mysql 
  register: dir_files

- shell: /etc/init.d/mariadb setup
  when: dir_files.matched|int  < 1 

- name: service  MariaDB configuration
  service:
    name: mariadb
    state: started
    enabled: true

- name: Sets the root password 
  mysql_user: user=root password= "{{ mysql_root_password }}" host=localhost
  no_log: True

- name: Deletes anonymous MySQL server user for ansible_fqdn
  mysql_user: user="" host= "{{ ansible_fqdn }}" state="absent"
  no_log: True

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent"
  no_log: True

- name: Secures the MySQL root user for IPV6 localhost (::1)
  mysql_user: user="root" password= "{{ mysql_root_password }}" host="::1"
  no_log: True

- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user: user="root" password= "{{ mysql_root_password }}" host="127.0.0.1"
  no_log: True

- name: Secures the MySQL root user for localhost domain (localhost)
  mysql_user: user="root" password= "{{ mysql_root_password }}" host="localhost"
  no_log: True

- name: Secures the MySQL root user for server_hostname domain
  mysql_user: user="root" password= "{{ mysql_root_password }}" host= "{{ ansible_fqdn }}"
  no_log: True

- name: Removes the MySQL test database
  mysql_db: db=test state=absent

- name:  install python
  apk:
    name:  python2
    state: present

      
- name: Install  python support MariaDB  from a 3.10 community repository
  community.general.apk:
    name: py-mysqldb
    state: latest
    update_cache: yes
    repository: http://mirror.yandex.ru/mirrors/alpine/v3.10/community


